### PR TITLE
Adding check-manifest

### LINKED ISSUE #22: tests: introduce check-manifest

### PR DESCRIPTION
**Pull request by accraze**
This PR adds `check-manifest` to your tox.ini file.

check-manifest will be run at the start of `testenv:release`

Fixes #22

### CODE REVIEW

**Comment by jirikuncar** [comment]
@accraze Thanks! Can you also include `check-manifest` in `./run-tests.sh`?

(see our cookiecutter template https://github.com/inveniosoftware/cookiecutter-invenio-module/blob/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/run-tests.sh)

- [ ] Please consider adding yourself to `AUTHORS.rst`
- [ ] Please reply if you agree to donate this (and any future) contributions to *cernservicexml* package under the terms of the Revised BSD Licence.

**Comment by tiborsimko** [comment]
LGTM

(Testing only, trying to see what happens when one "imposes" non-maintainer approval...)

**Comment by tiborsimko** [comment]
> Testing only, trying to see what happens when one "imposes" non-maintainer approval...

Good, it was rejected.  Hence, when a local MAINTAINERS file exists in a repository, the global organisation maintainers team doesn't count.

**Comment by accraze** [comment]
@jirikuncar I added it to run-tests and added myself to authors.

I agree to donate this (and any future) contributions to cernservicexml package under the terms of the Revised BSD Licence

**Comment by jirikuncar** [comment]
LGTM

**Pull request merged**
